version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/examples/react/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/examples/javascript/"
  schedule:
    interval: daily