version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/examples/react/"
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/examples/javascript/"
  schedule:
    interval: monthly
