name: Code Formatting Check

on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --trailing-comma none examples *.md typescript/**/* !examples/angular/src/app/examples/code-examples.ts !examples/*/build !examples/*/dist !examples/*/.angular